on:
  workflow_dispatch:
  pull_request:
    branches: 
    - main
    - master
name: Release
jobs:
    release-job:
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash
          working-directory: ./packaging
      steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Run a script
        run: ./doPackage.sh
      - name: Release
        uses: phuonghuynh/action-ghrelease@v1.1.0
        with:
          files: packaging/social-backgrounds-*.sh
          tag_name: ${{ env.RELEASE_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
